## 1. Numpy
### 1.1 Numpy 배열

In [3]:
import numpy as np

- numpy n-dim array(ndarray) vs list

In [6]:
l = [1, 2, 3, 4, 5]
l * 2


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
n = np.array([1, 2, 3, 4, 5])
n * 2

array([ 2,  4,  6,  8, 10])

In [8]:
# 모든 수의 제곱수
[i * i for i in l]

[1, 4, 9, 16, 25]

In [9]:
np.square(n)

array([ 1,  4,  9, 16, 25])

- 1차원 배열(Vector)

In [10]:
# Array 형태인 list, tuple 가능
a = np.array((1, 2, 3, 4, 5))
type(a)

numpy.ndarray

In [11]:
# a의 데이터타입, 모양, 차원수, 크기
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (5,), 1, 5)

In [13]:
# 벡터화 연산
a * 2

array([ 2,  4,  6,  8, 10])

In [12]:
b = np.array([10, 20, 30, 40, 50])
c = 2 * a + b
c

array([12, 24, 36, 48, 60])

In [14]:
a == 2

array([False,  True, False, False, False])

In [15]:
b > 20

array([False, False,  True,  True,  True])

- 2차원 배열(Matrix)

In [17]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
c = np.arange(1, 7).reshape(2, 3)   # reshape => c.shape
c

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor)

In [33]:
d = np.arange(1, 25).reshape(2, 3, 4)   # plane, row, column
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [25]:
d.dtype, d.shape, d.ndim, d.size

(dtype('int32'), (3, 3, 3), 3, 27)

- 배열의 인덱싱 

In [26]:
a

array([1, 2, 3, 4, 5])

In [27]:
# Vector
a[0], a[3], a[-1]

(1, 4, 5)

In [28]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Matrix
c[0][0], c[0, 0]    # only numpy

(1, 1)

In [30]:
c[1, 0], c[0, -1], c[-1, -1]

(4, 3, 6)

In [34]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [37]:
# Tensor
# 9, 20
d[0, -1, 0], d[-1, 1, -1]

(9, 20)

- 배열의 슬라이싱

In [38]:
# 리스트에서는 행, 열 슬라이싱이 동시에 안됨
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [39]:
l[:2][:2] # ❌

[[1, 2, 3], [4, 5, 6]]

In [40]:
l[1][:2]

[4, 5]

In [42]:
c = np.arange(1, 13).reshape(3, 4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
# 위 2개의 행
c[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
# 오른쪽 두 열
c[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [52]:
c[:-1, 1:3]

array([[2, 3],
       [6, 7]])

In [53]:
c[:2, ::2]

array([[1, 3],
       [5, 7]])

In [81]:
m = np.array([[0, 1, 2, 3, 4],  
            [5, 6, 7, 8, 9],
            [10, 11, 12, 13, 14]])

In [82]:
# 연습문제: 찾기 7, 14, [6, 7], [7, 12], [[3, 4], [8, 9]]
m[1, 2], m[-1, -1], m[1, 1:3], m[1:3, 2], m[:2, 3:]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

In [83]:
# 맨 마지막 열이  y, 나머지는 X
X = m[:, :-1]
y = m[:, -1]    # 1차원은 소문자, 2차원 이상은 대문자

- 배열 인덱싱(Fancy indexing)

In [85]:
# idx값이 True/False이면, True값이 있는 곳의 원소만 통과(Filter)
print(a)
idx = np.array([True, False, True, True, False])
print(a[idx])

[1 2 3 4 5]
[1 3 4]


In [86]:
# 홀수만 통과
a[a % 2 == 1]

array([1, 3, 5])

In [87]:
# 3보다 큰 수만 통과
a[a > 3]

array([4, 5])

In [88]:
# idx값이 정수(인덱스)면 해당 인덱스의 원소가 선택
idx = np.array([1, 2, 4])
a[idx]

array([2, 3, 5])

In [97]:
# 연습문제3
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 3의 배수, 4로 나누면 1이 남는수, 3으로 나누면 나누어지고 4로 나누면 1이 남는수
x[x % 3 == 0], x[x % 4 == 1], x[(x % 3 == 0) & (x % 4 == 1)]

(array([ 3,  6,  9, 12, 15, 18]), array([ 1,  5,  9, 13, 17]), array([9]))

In [98]:
# 위의 결과는 ndarray. 원소의 값을 꺼내려면 다시 인덱싱
x[(x % 3 == 0) & (x % 4 == 1)][0]

9