### 1.3 배열의 연산(Operation)

In [1]:
import numpy as np

- 벡터화 연산

In [2]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [5]:
# 연산 시간 측정
%%time
z = np.empty_like(x)
for i in range(100000):
    z[i] = x[i] + y[i]

CPU times: total: 46.9 ms
Wall time: 46 ms


In [9]:
%time z = x + y

CPU times: total: 0 ns
Wall time: 998 µs


In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [12]:
a >= b

array([False,  True,  True,  True])

In [13]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [14]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [15]:
5 * a

array([ 5, 10, 15, 20])

In [16]:
5 + a

array([6, 7, 8, 9])

- 차원 축소 연산

In [17]:
x = np.arange(1, 5)
np.sum(x)

10

In [18]:
# method 형태로도 가능
x.sum()

10

In [20]:
# 최소, 최대, 평균
x.min(), x.max(), x.mean()

(1, 4, 2.5)

In [21]:
# 대표값: 평균, 중앙값
np.mean(x), np.median(x)

(2.5, 2.5)

In [22]:
# 통계: 분산, 표준편차
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [25]:
# 최소값, 최대값의 인덱스
np.argmin(x), np.argmax(x)

(0, 3)

- all / any

In [26]:
np.all(np.array([True, True, False])), np.any(np.array([True, True, False]))

(False, True)

In [27]:
# a == a 원소 비교
np.all(a == a)

True

- 2차원 이상의 연산

In [29]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# 모든 원소의 합 과 평균
np.sum(a), np.mean(a)

(21, 3.5)

- axis = 0 가로축 기준으로 계산
- axis = 1 세로축 기준으로 계산

In [32]:
# axis = 0, 각 좌표(row, col)에서 row를 기준으로 합과 평균
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [33]:
# axis = 1, 각 좌표(row, col)에서 col을 기준으로 합과 평균
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [40]:
b = np.arange(1, 13).reshape(2, 2, -1)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
np.sum(b, axis=0), np.mean(b, axis=0)

(array([[ 8, 10, 12],
        [14, 16, 18]]),
 array([[4., 5., 6.],
        [7., 8., 9.]]))

In [42]:
np.sum(b, axis=1), np.mean(b, axis=1)

(array([[ 5,  7,  9],
        [17, 19, 21]]),
 array([[ 2.5,  3.5,  4.5],
        [ 8.5,  9.5, 10.5]]))

In [43]:
np.sum(b, axis=2), np.mean(b, axis=2)

(array([[ 6, 15],
        [24, 33]]),
 array([[ 2.,  5.],
        [ 8., 11.]]))

- 연습문제 3.3.1

In [45]:
# Data
np.random.seed = 2023
x = np.round(np.random.random(30).reshape(5, 6) * 10, 4)
x

array([[1.9008, 1.0189, 9.5938, 8.8141, 8.4163, 0.1113],
       [7.7771, 5.9802, 3.1365, 9.2067, 0.1236, 8.7857],
       [1.1319, 5.145 , 6.062 , 8.4422, 1.7908, 9.5462],
       [1.3728, 7.5313, 3.362 , 3.4359, 9.1163, 3.802 ],
       [5.817 , 5.4963, 7.142 , 1.3614, 0.1513, 4.134 ]])

In [46]:
# 1. 전체의 최댓값
np.max(x)

9.5938

In [48]:
# 2. 각 행의 합
np.sum(x, axis=1)

array([29.8552, 35.0098, 32.1181, 28.6203, 24.102 ])

In [50]:
# 3. 각 행의 최댓값
np.max(x, axis=1)


array([9.5938, 9.2067, 9.5462, 9.1163, 7.142 ])

In [51]:
# 4. 각 열의 평균
np.mean(x, axis=0)

array([3.59992, 5.03434, 5.85926, 6.25206, 3.91966, 5.27584])

In [53]:
# 5. 각 열의 최솟값
np.min(x, axis=0)

array([1.1319, 1.0189, 3.1365, 1.3614, 0.1236, 0.1113])

- 정렬(sort)

In [54]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [55]:
np.sort(a)      # default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [56]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [60]:
# 내림차순 정렬, axis=1의 경우
np.sort(a, axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [61]:
# 내림차순 정렬, axis=0의 경우
np.sort(a, axis=0)[::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [64]:
# sort()는 자기 파괴적(inplace) method
a.sort(axis=1)

In [65]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [69]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [107]:
a[j]

array([12, 25, 38, 42])

- 연습문제 3.3.2

In [120]:
#다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다.
#영어 성적을 기준으로 각 열(column)을 재정렬하라.
score = np.array([[  1,    2,    3,    4],
                    [ 46,   99,  100,   71],
                    [ 81,   59,   90,  100]])
score_eng1 = score[:, score[1].argsort()][:, ::-1]

score_eng2 = score[:, np.argsort(score[1])][:, ::-1]

score_eng3 = score[:, [0, 3, 1, 2]][:, ::-1]

score_eng2, score_eng1, score_eng3, score[1].argsort()


(array([[  3,   2,   4,   1],
        [100,  99,  71,  46],
        [ 90,  59, 100,  81]]),
 array([[  3,   2,   4,   1],
        [100,  99,  71,  46],
        [ 90,  59, 100,  81]]),
 array([[  1,   4,   2,   3],
        [ 46,  71,  99, 100],
        [ 81, 100,  59,  90]]),
 array([0, 3, 1, 2], dtype=int64))